### ISSUE TITLE
Hi ^^~! How can i recevice??

### ISSUE THREAD

**Issue by BBUBBA** [limpo1989/kcp-csharp#10]
i try test.. this project ^^

Send function is good

but... mRecvBuffer.ReadableBytes not work.....

how can i use this?

**Comment by limpo1989** [comment]
What do you mean by 'not work`? got Exception? 
Please see how the example are used. [Sample/Main.cs](https://github.com/limpo1989/kcp-csharp/blob/master/Sample/Main.cs)

**Comment by BBUBBA** [comment]
Thanks !!! Reply For me ^^
