### ISSUE TITLE
崩溃异常

### ISSUE THREAD

**Issue by yushengery** [limpo1989/kcp-csharp#13]
你好，我们用了这个库，用了最新的commit，7ed200bb258b7b1e54046a527bf9a91921c2e248
我们会在每一帧调用Update函数，但是今天发现有崩溃的问题，堆栈如下：
NullReferenceException: Object reference not set to an instance of an object
KcpProject.KCP.Flush (System.Boolean ackOnly) (at Assets/Framework/ThirdParty/KCP/KCP.cs:917)
KcpProject.KCP.Update () (at Assets/Framework/ThirdParty/KCP/KCP.cs:1005)
KcpProject.UDPSession.Update () (at Assets/Framework/ThirdParty/KCP/UDPSession.cs:151)
Framework.KCPClient.OnUpdateTick () (at Assets/Framework/CSharp/Network/KCPClient.cs:47)

**Comment by limpo1989** [comment]
* 确定<b>没有</b>多线程调用API
* 提供一个最小的可复现的例子，如果不能稳定复现尝试调试看看

从提供的信息来看似乎是Segment被reset之后还在使用导致问题，建议检查多线程方面的问题

**Comment by yushengery** [comment]
请问这些Read、Write、Update这些函数调用都需要保证线程安全吗？

**Comment by limpo1989** [comment]
是的 不保证线程安全, 需要你自己保证

**Comment by yushengery** [comment]
好的，谢谢，我们已经修改了，再观察一下
