### ISSUE TITLE
Add LICENSE to project

### ISSUE THREAD

**Issue by JamJar00** [limpo1989/kcp-csharp#19]
Hi there,

Thanks for providing a good implemetation of KCP for .NET!

Are you able to add a license to the project so that people can use it? [By default a repository without a license is not usable without risk of legal action etc.](https://choosealicense.com/no-permission/)

[KCP is MIT licensed](https://github.com/skywind3000/kcp/blob/master/LICENSE) so it would be nice to follow suit, but obviously that is your choice!

Jamie

**Comment by limpo1989** [comment]
Thank you for your reminder. commit: 4d39631cffff8eb3a5678aaf6ad2630950f8302c

**Comment by JamJar00** [comment]
Much appreciated!
