### ISSUE TITLE
发送数据一段时间后会报错

### ISSUE THREAD

**Issue by andyhebear** [limpo1989/kcp-csharp#4]
我在unity5中重新写了一个测试客户端
https://github.com/RainsSoft/kcp-csharp/
测试了一天，内存稳定，没有报错，不过测试代码较为简单

**Comment by limpo1989** [comment]
kcp-csharp客户端写的比较随意，主要是为了演示如何接入，实际使用还是要自己写客户端的，这里的主要是一个参考。
