### ISSUE TITLE
减少内存分配次数？

### ISSUE THREAD

**Issue by qi7chen** [limpo1989/kcp-csharp#6]
kcp.cs里用append()和slice()来操作Segment[](rcv_que, snd_que,rcv_buf, snd_buf)，而每次append和slice都会重新分配内存。
是否可以考虑使用一个nrcv_que来表示实际长度，而snd_buf.Length只表示capacity，这样修改长度的时候只需要调整nrcv_que的指向位置，不必产生大量的内存分配

**Comment by limpo1989** [comment]
GC优化已经提交 [GC optimized](https://github.com/limpo1989/kcp-csharp/commit/714f92b044e38439ad6bc1b9c676b2a85224cd4f)
