### ISSUE TITLE
udp断线问题

### ISSUE THREAD

**Issue by 7891liang** [limpo1989/kcp-csharp#9]
void init_kcp(UInt32 conv)
        {
            mKcp = new KCP(conv, (byte[] buf, int size) =>
            {
              //这里偶现的会报异常，Socket has bean shut down，这里建议怎么处理呢
               mUdpClient.Send(buf, size);
            });

            // fast mode.
            mKcp.NoDelay(1, 10, 2, 1);
            mKcp.WndSize(128, 128);
        }

**Comment by limpo1989** [comment]
测试例子已经更新，简单判断一下 Connected 之后在发送
